### ISSUE TITLE
[Feature Request] Mod Menu config support and/or "/stars reload" command

### ISSUE THREAD

**Issue by Abbanon** [b3spectacled/custom-stars#1]
As the title implies, I'm requesting two features if possible:
- The ability to modify the `config/customstars.json` file via the Mod Menu mod
- The ability to use a command like `/stars reload` to reload the mod's config and instantly apply changes, without having to relaunch the game

**Comment by b3spectacled** [comment]
Following up on this since I just added it, v0.3.2 now lets you change the base settings (size/count) without having to restart the game.
