### ISSUE TITLE
Update Custom Void and Custom Stars to 1.19

### ISSUE THREAD

**Issue by StereoMadnessss** [b3spectacled/custom-stars#11]
The title explains what it is

**Comment by ghost** [comment]
Hello, yes please - we need that mod <3
Thanks.

**Comment by b3spectacled** [comment]
Updated Custom Stars, Custom Void will follow shortly.

**Comment by ghost** [comment]
Hello, thank you 🥰

**Comment by b3spectacled** [comment]
Updated Custom Void to 1.19, thanks for your patience.
