### ISSUE TITLE
[Bug Report] Custom Stars v0.3 causes crash on startup

### ISSUE THREAD

**Issue by Abbanon** [b3spectacled/custom-stars#3]
As the title implies, trying to load Custom Stars v0.3 causes a crash on startup.
Here's a link to the crash report: https://paste.ee/p/eZoGt
v0.1, v0.2, and v0.2.1 all work perfectly fine. It's only v0.3 that has this issue.

**Comment by b3spectacled** [comment]
Sorry about that.  I think I know what the issue is, can you try this and see if it fixes the problem? https://github.com/b3spectacled/custom-stars/releases/tag/v0.3.1

Thanks.

**Comment by Abbanon** [comment]
That build does indeed work as intended! Thank you for the quick response!
