### ISSUE TITLE
Bug with spyglass and star scaling

### ISSUE THREAD

**Issue by AzureMonument** [b3spectacled/custom-stars#7]
So in 1.17.1, when you're not using the spyglass, stars appear as normal.

Small tiny, as they should.
![2021-08-13_12 16 57](https://user-images.githubusercontent.com/43318292/129389104-782939bc-8aab-45f4-b248-40e2d7b111cb.png)

But when you _do_ use the spyglass... well.
![2021-08-13_12 17 03](https://user-images.githubusercontent.com/43318292/129389147-f5907149-0951-4248-85aa-bd7017e33214.png)

Stars should _not_ scale like this. This is terrifying on an existential level. Pls fix.
And thanks for the mod~♪

**Comment by b3spectacled** [comment]
I'm not sure what the bug is here, the stars are rendered at a fixed distance from the player like a skybox.  You'd get the same effect with the vanilla star rendering.

You could just reduce the overall size of the stars.

> This is terrifying on an existential level.

Well, you are playing a game where everything is some form of cuboid. :)
