### ISSUE TITLE
[Feature-request] Allowing changing of the night sky color in the overworld. 

### ISSUE THREAD

**Issue by Xrey274** [b3spectacled/custom-stars#8]

**Comment by b3spectacled** [comment]
Added with 52004d4, see the latest release. Thanks for the suggestion!

**Comment by Xrey274** [comment]
![image](https://user-images.githubusercontent.com/30723811/141166134-c575a056-4120-4620-9a37-ff4ac116eb1e.png)
Seems there is still some work to do. The fog in the sky looks really bad at night, kinda ruining the sky (see image).

**Comment by Xrey274** [comment]
![image](https://user-images.githubusercontent.com/30723811/141166583-3b603310-638c-40b3-9e46-4a9eaefe8d02.png)
More obvious with a lighter color.
